name: Generate images.json

on:
  push:
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate images.json
      run: |
        python generate_images_json.py

    - name: Commit and push images.json
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add images.json
        git commit -m 'Update images.json'
        git push
