name: Generate JSON Data

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate JSON
        run: |
          echo '{"message": "Hello, World!"}' > output.json

      - name: Upload JSON as artifact
        uses: actions/upload-artifact@v2
        with:
          name: json-data
          path: output.json
